[package]
name = "url-vault-viewer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
html-escape.workspace = true
html5ever.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tiny_http.workspace = true
ureq.workspace = true
url.workspace = true
url-vault-core = { path = "../url-vault-core" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
